version: '2'

services:
  nginx:
    image: nginx:1.10-alpine
    volumes:
      - ".:/var/www/html:ro"
      - "./nginx:/etc/nginx/conf.d:ro"
    depends_on:
      - php
    ports:
      - "8080:80"

  php:
    image: greut/laravel:latest
    build: .
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=forge
      - DB_USERNAME=forge
      - DB_PASSWORD=forge
      - BROADCAST_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
      - mail
    volumes:
      - ".:/var/www/html"

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=forge
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

volumes:
  mysql:
  redis:
